name: manual-pull-DM-catalogue
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Manual-Pull-DM-Catalogue:
    runs-on: ubuntu-latest
    steps:
      - run: echo Starting...
      - name: Gets latest DM catalogue
        run: node api.js
        working-directory: science
